// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { ThemeProvider } from '@/components/contexts/theme-context';
import BodyComponent from '@/components/contexts/BodyComponent';
import Container from '@/components/Container';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <BodyComponent>
          <Navbar />
          <Container>
            {children}
          </Container>
        </BodyComponent>
      </ThemeProvider>
    </html>
  );
}
