import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar, Footer } from "@/components/HeadFoot";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next-Concepts",
  description: "Generated by create next app using bun",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-900 text-white`}>
        <main>
          <Navbar />
            {children}
          <Footer />
        </main>
        </body>
    </html>
  );
}
